FROM golang:1.23-bookworm

WORKDIR /app

RUN go install github.com/air-verse/air@v1.61.7

COPY go.mod go.sum* ./
RUN if [ -f go.mod ]; then go mod download; fi

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
